+incdir+$ROOT_PATH/rtl

-sverilog
$ROOT_PATH/rtl/AMBA_INTF.sv
$ROOT_PATH/rtl/STREAM_INTF.sv

$ROOT_PATH/rtl/AIDC_TOP.sv
$ROOT_PATH/rtl/SOP_GEN.sv


$ROOT_PATH/rtl/COMP_TOP.sv
$ROOT_PATH/rtl/COMP_MUX.sv
$ROOT_PATH/rtl/COMP_ENGINE.sv
$ROOT_PATH/rtl/COMP_INTF.sv

$ROOT_PATH/rtl/BPC_COMP.sv
$ROOT_PATH/rtl/BPC_DBX_ENC.sv
$ROOT_PATH/rtl/BPC_CODEBUF.sv
$ROOT_PATH/rtl/SR_COMP.sv
$ROOT_PATH/rtl/ZRLE_COMP.sv
$ROOT_PATH/rtl/ZRLE_CODEBUF.sv

$ROOT_PATH/rtl/DECOMP_TOP.v
$ROOT_PATH/rtl/DECODER_GROUP.sv
$ROOT_PATH/rtl/ZRLE_DECOMP.sv
$ROOT_PATH/rtl/SR_DECOMP.sv
$ROOT_PATH/rtl/BPC_DECOMP.sv

$ROOT_PATH/rtl/FIFO.v
$ROOT_PATH/rtl/FIFO_66.v

